### ISSUE TITLE
Some more to add 

### ISSUE THREAD

**Issue by CleanMachine1** [Itai-Nelken/aptpac#1]
I have recently switched to running Arch and have some suggestions.

I have been clearing dependencies which are unneeded and the command for that is

sudo pacman  -R $(pacman Q-dtq)

and just for orphan dependencies you just run the same but run what is it inside of the brackets.

I know this feature isn't a thing with apt but it is still a useful command

PS: do you actually use Arch

**Comment by Itai-Nelken** [comment]
>PS: do you actually use Arch

I use it a bit on my pi4 when I need ode stuff, and from today on my new PineBook Pro

**Comment by Itai-Nelken** [comment]
I think I already added that, but used a slightly different command I got from [here](https://wiki.archlinux.org/index.php/Pacman/Rosetta)
 https://github.com/Itai-Nelken/aptpac/blob/3a6f16cf87a6a2dc173a06a6d277c01815dc877c/aptpac.sh#L101-L104

**Comment by Itai-Nelken** [comment]
that removes unneeded packages, the equivalent of `apt autoremove`

BTW can you test the C version? I just made it get all the packages after the command, so `apt pac install package1 package2` instead of `apt pac install "package1 package2"`. the bash version already does that for some time.

**Comment by CleanMachine1** [comment]
That pinebook is a little bit more money, should of picked a thinkpad

**Comment by CleanMachine1** [comment]
Ill give it a look later

**Comment by CleanMachine1** [comment]
> > PS: do you actually use Arch
> 
> I use it a bit on my pi4 when I need ode stuff, and from today on my new PineBook Pro

Are you using actual arch or manjaro

**Comment by Itai-Nelken** [comment]
> > > PS: do you actually use Arch
> > 
> > 
> > I use it a bit on my pi4 when I need ode stuff, and from today on my new PineBook Pro
> 
> Are you using actual arch or manjaro

manjaro, forgot to mention that.

**Comment by Itai-Nelken** [comment]
> That pinebook is a little bit more money, should of picked a thinkpad

I needed a new smaller laptop with a battery that actually lasts, and I wanted a pinebookpro, and the pinebookpro can do everything I need. so I bought it.

**Comment by Itai-Nelken** [comment]
I'm closing this as the feature you asked for is already implemented. feel free to reply with any questions you have.

**Comment by CleanMachine1** [comment]
Re open this please.

I have run read and run the code and the C version is pretty impressive.

You NEED to implement:
show
purge

**Comment by Itai-Nelken** [comment]
moving your 'learning mode' feature request to here @CleanMachine1

**Comment by Itai-Nelken** [comment]
**summary of all feature requests oin this issue and progress on them:**
- `purge`
- `show`

@CleanMachine1 what do you mean by `show`? what do you mean it to do?

**Comment by Itai-Nelken** [comment]
added both commands :)

**Comment by Itai-Nelken** [comment]
actually 3 commands:
`purge`, `how`, & `show-all`

**Comment by CleanMachine1** [comment]
How?

**Comment by CleanMachine1** [comment]
Nevermind
