### ISSUE TITLE
how to compile C version? + 'learn the commands' mode feature request

### ISSUE THREAD

**Issue by CleanMachine1** [Itai-Nelken/aptpac#2]

**Comment by Itai-Nelken** [comment]
## `cmake`.
1) `pacman -S cmake make gcc git`<br>
2) `git clone https://github.com/Itai-Nelken/aptpac.git`<br>
3) `cd aptpac/C-edition`<br>
4) `mkdir build, cd build; cmake ..`<br>
5) `make`<br>
run directly without installing: `./aptpac`
**install:** `sudo make install`
**uninstall:** from the build folder, run `sudo make uninstall`

**Comment by CleanMachine1** [comment]
I will create some documentation

**Comment by Itai-Nelken** [comment]
thanks!
please create it in the /C-edition/ folder for now, I'll move it to the root of the repo once I'm happy replacing the bash edition with the C edition.

**Comment by CleanMachine1** [comment]
Really impressive code, I was more thinking adding a documentation.txt then having the README.md file using a hyperlink to it

**Comment by CleanMachine1** [comment]
I am really interested in this project, I would really want to help you.

I am going to watch this project and do some PR.

I plan on adding more documentation and maybe some help on learning the arch commands rather than just living with aptpac

Also when I first saw this repo, I thought it was an arch cover for apt rather the opposite so I will fix that

Anyway, right now I am going to fix on adding and making the README better

**Comment by Itai-Nelken** [comment]
Thanks a lot!
If you pass over the bash script (as its easier to read) you will probably learn all the commands you need to know.

**Comment by CleanMachine1** [comment]
The PR is fully done, I will use aptpac however I shouldn't as I should learn the actual commands through practice 

Maybe you should print the command being used whenever a certain one is being done

EG

$ aptpac install gparted

The Arch equivalent is 
sudo pacman -S gparted

**Comment by Itai-Nelken** [comment]
Good idea, but I'm going to add it as a 'learn the commands mode'.

**Comment by CleanMachine1** [comment]
precisely

**Comment by Itai-Nelken** [comment]
### progress on the 'learning mode':
I added it but you have to add a flag to cmake to compile `aptpac` with it. the flag is `-DLEARN=1`
so `cmake -DLEAERN=1 ..`

I also added the `-DCALLCOMMAND="./aptpac` so I can change it to `aptpac` when building a build I want to install. also when compiling a build you should use `-DCMAKE_BUILD_TYPE=Release`, it removes all the debug stuff and makes a executable that is way smaller.

**Comment by CleanMachine1** [comment]
Is it added?

**Comment by CleanMachine1** [comment]
Also where are the relevant commits?

**Comment by Itai-Nelken** [comment]
haven't pushed it yet.

**Comment by Itai-Nelken** [comment]
as of commit 04255b2a4094ff10d4178a759def2627416650d7

**Comment by Itai-Nelken** [comment]
As of commit ecbe23af9aaa6f4e5817ab99aca3e2a2a3a24957 the bash version has the ability to save the setting!
You can turn the setting on by running `aptpac --learning-mode=on` and turn it off by running `aptpac --learning-mode=off`. when entering the main while loop, the script will load all the settings and export them to a variable called `SETTING`, then in a `case` statement (before the main one) will load each setting. for now it only works with one setting, but I have added the ability to load single settings (not tested yet) so I can implement multiple settings in the future.

**Comment by Itai-Nelken** [comment]
I'm closing this issue and opening a new one for 'learning mode'.

**Comment by Itai-Nelken** [comment]
continued in #14
