### ISSUE TITLE
PKGBUILD?

### ISSUE THREAD

**Issue by CleanMachine1** [Itai-Nelken/aptpac#24]
A PKGBUILD would allow it to be put into the AUR giving it a potential bigger audience.

I would be willing to create one.

Or it maybe useful to make your own, so you can learn if you haven't, DollarSkip's PKGBUILD seems to fit exactly

**Comment by Itai-Nelken** [comment]
Actually I have already created one some time ago based on the webcord one: https://github.com/Itai-Nelken/aptpac/blob/main/C-edition/PKGBUILD

Thanks for the suggestion!
A problem is that there already is a app called aptpac in the AUR...

**Comment by CleanMachine1** [comment]
Why not just call it aptpac-c

**Comment by Itai-Nelken** [comment]
good idea!

**Comment by Itai-Nelken** [comment]
I added a script that generates a PKGBUILD for the C-edition. the PKGBUILD generated is based on the DollarSkip one, si thanks @cleanmachine1!
commit 6b6efea072ca3fea01b828eca324bf47a8fea722
